services:
  _defaults:
    autowire: true
    autoconfigure: true

  GAYA\PrivateDownload\:
    resource: '../Classes/*'

  GAYA\PrivateDownload\EventListener\GeneratePublicUrlForResource:
    tags:
      - name: event.listener
        identifier: 'generatePublicUrlForResource'
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent
